inherit_from: .rubocop_todo.yml

inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'

Metrics/AbcSize:
  Exclude:
    - 'lib/ouranos/provider/bundler_capistrano.rb'
    - 'lib/ouranos/provider/default_provider.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/lib/ouranos/comparison/default_spec.rb'
    - 'spec/lib/ouranos/comparison/linked_spec.rb'
    - 'spec/lib/ouranos/notifier/slack_spec.rb'
    - 'spec/lib/ouranos/provider/default_provider_spec.rb'
    - 'spec/controllers/concerns/webhook_validations_spec.rb'
    - 'spec/receivers/lock_receiver_spec.rb'
    - 'spec/requests/events_spec.rb'
    - 'spec/requests/site_spec.rb'
    - 'spec/services/environment_locker_spec.rb'
    - 'spec/models/deployment/output_spec.rb'
    - 'spec/lib/ouranos/jobs/deployment_spec.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/ouranos/notifier/default.rb'
    - 'lib/ouranos/provider/default_provider.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/ouranos/provider/capistrano.rb'
    - 'lib/ouranos/provider/bundler_capistrano.rb'
    - 'lib/ouranos/provider/default_provider.rb'
    - 'lib/ouranos/provider/shell.rb'
    - 'lib/ouranos/notifier/slack.rb'
    - 'lib/ouranos/notifier/default.rb'
    - 'app/models/deployment/credentials.rb'
    - 'spec/support/helpers/deployment_status_helper.rb'
    - 'spec/support/helpers/gist_helper.rb'
    - 'spec/support/helpers/meta_helper.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/lib/ouranos/provider_spec.rb'
    - 'spec/lib/ouranos/jobs/environment_locked_error_spec.rb'
    - 'spec/lib/ouranos/notifier/slack_spec.rb'
    - 'spec/lib/ouranos/comparison/default_spec.rb'
    - 'spec/lib/ouranos/comparison/linked_spec.rb'
    - 'spec/receivers/lock_receiver_spec.rb'
    - 'spec/services/environment_locker_spec.rb'

RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/support/helpers/gist_helper.rb'
    - 'spec/support/helpers/meta_helper.rb'
