inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'

Metrics/ClassLength:
  Exclude:
    - 'lib/ouranos/notifier/default.rb'
    - 'lib/ouranos/provider/default_provider.rb'

Metrics/AbcSize:
  Exclude:
    - 'lib/ouranos/provider/bundler_capistrano.rb'
    - 'lib/ouranos/provider/default_provider.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/ouranos/provider/capistrano.rb'
    - 'lib/ouranos/provider/bundler_capistrano.rb'
    - 'lib/ouranos/provider/default_provider.rb'
    - 'lib/ouranos/provider/shell.rb'
    - 'lib/ouranos/notifier/slack.rb'
    - 'lib/ouranos/notifier/default.rb'
